### ISSUE TITLE
Game keeps closing out

### ISSUE THREAD

**Issue by drugoo85** [CompleteMonochrome/ddlctrueroute#14]
Every time in the Sayori or Inauguration day arc I get to the 2nd distorted memory, no matter what choices I make, no matter what routes I took to get there, the game closes me out. "Turn it off" always happens no matter what choices I make. Is this the end of the game? If so that is a terrible ending. If not, then how are we supposed to proceed?

**Comment by CompleteMonochrome** [comment]
That's not the ending, the mod isn't finished yet. Check your game files for a hint.

**Comment by drugoo85** [comment]
I found out what to do, but those hints didn't show up before for some reason. I had to delete a ton of files, restore characters that were deleted and load the very last save, the one where Ayame lets you decide who to take. The messages of waiting just started to appear while I had the game up and the folder up, right before I chose who to go with. I know I searched that folder for hints before and those weren't there but for some reason they showed up now.

**Comment by AnimeMizuki-Weeb** [comment]
I also have the problem whenever they say "Shut it off" and no matter what choice I choose, it'll just be the same outcome. So when will they ever finish the mod? It's been like 2 years or something. Is there ever a way to actually get past this part??

**Comment by AnimeMizuki-Weeb** [comment]
Oh nevermind, I actually found out what to do to proceed
